- name: Check supported OS
  when: 'linux_server_os not in ["debian-10", "debian-11", "raspi"]'
  fail: msg='Unsupported OS.'

- name: Get service facts
  service_facts: {}
  register: service_facts

- import_tasks: basic_packages.yml
- import_tasks: iptables.yml
- import_tasks: fail2ban.yml
- import_tasks: logging.yml
- import_tasks: networking.yml
- import_tasks: dns.yml
- import_tasks: ntp.yml
- import_tasks: hostname.yml
- import_tasks: hidepid.yml
- import_tasks: sudo.yml
- import_tasks: users.yml
- import_tasks: l10n.yml
- import_tasks: banner.yml
- import_tasks: sshd.yml
- import_tasks: vim.yml
