# Setup sudo

- name: Disable password for ansible user
  when: 'linux_server_ansible_user_sudo_no_pass'
  lineinfile:
    path: '/etc/sudoers'
    backup: yes
    regexp: '^{{ linux_server_ansible_user}}\s.+$'
    line: '{{ linux_server_ansible_user }} ALL=(ALL:ALL) NOPASSWD: ALL'
    insertafter: '^%sudo\s.+$'
    validate: 'visudo -c %s'
