- name: Install NUT
  apt:
    name:
      - nut

- name: Setup nut.conf
  template:
    src: nut.conf.j2
    dest: /etc/nut/nut.conf
    group: nut
    mode: '0644'
  notify:
    - Restart nut-driver.service
    - Restart nut-server.service
    - Restart nut-monitor.service

- name: Setup ups.conf (primary)
  when: 'nut_primary'
  template:
    src: ups.conf.j2
    dest: /etc/nut/ups.conf
    group: nut
    mode: '0644'
  notify:
    - Restart nut-driver.service
    - Restart nut-server.service
    - Restart nut-monitor.service

- name: Setup upsd.conf (primary)
  when: 'nut_primary'
  template:
    src: upsd.conf.j2
    dest: /etc/nut/upsd.conf
    group: nut
    mode: '0640'
  notify:
    - Restart nut-server.service
    - Restart nut-monitor.service

- name: Setup upsd.users (primary)
  when: 'nut_primary'
  template:
    src: upsd.users.j2
    dest: /etc/nut/upsd.users
    group: nut
    mode: '0640'
  notify:
    - Restart nut-server.service
    - Restart nut-monitor.service

- name: Setup upsmon.conf
  template:
    src: upsmon.conf.j2
    dest: /etc/nut/upsmon.conf
    group: nut
    mode: '0640'
  notify:
    - Restart nut-monitor.service

- name: Enable NUT driver (primary)
  when: 'nut_primary'
  systemd:
    name: nut-driver.service
    enabled: true
    masked: false
  notify:
    - Restart nut-driver.service

- name: Disable NUT driver (secondary)
  when: 'not nut_primary'
  systemd:
    name: nut-driver.service
    state: stopped
    enabled: false
    masked: true
  notify:
    - Reset failed nut-driver.service

- name: Enable NUT server (primary)
  when: 'nut_primary'
  systemd:
    name: nut-server.service
    enabled: true
    masked: false
  notify:
    - Restart nut-server.service

- name: Disable NUT server (secondary)
  when: 'not nut_primary'
  systemd:
    name: nut-server.service
    state: stopped
    enabled: false
    masked: true

- name: Enable NUT monitor
  systemd:
    name: nut-monitor.service
    enabled: true
    state: started
  notify:
    - Restart nut-monitor.service
