# Setup sudo

- name: Disable password for sudo group
  when: 'linux_server_sudo_no_pass'
  lineinfile:
    path: '/etc/sudoers'
    backup: true
    regexp: '^%sudo\s.+$'
    line: '%sudo ALL=(ALL:ALL) NOPASSWD: ALL'
    insertafter: '^%sudo\s.+$'
    mode: '0440'
    validate: 'visudo -c %s'

- name: Disable password for ansible user
  lineinfile:
    path: '/etc/sudoers'
    backup: true
    regexp: '^{{ linux_server_ansible_user }}\s.+$'
    line: '{{ linux_server_ansible_user }} ALL=(ALL:ALL) NOPASSWD: ALL'
    insertafter: '^%sudo\s.+$'
    mode: '0440'
    validate: 'visudo -c %s'
