# If storage should be configured
pve_storage_setup_enable: false
# (Required) Path to the storage config to copy.
# pve_storage_config_path: example/storage.cfg
# Storage names or dirs to use for different content types.
# Should probably be updated if using custom storage.
# (Using old vars for compatibility until the next major version.)
pve_storage_default_iso_name: '{{ pve_storage_default_iso_vztmpl_name | default("local") }}'
pve_storage_default_iso_path: '{{ pve_storage_default_iso_vztmpl_path | default("/var/lib/vz") }}'
pve_storage_default_image_name: '{{ pve_storage_default_image_rootdir_name | default("local-lvm") }}'
