# Enable the Traefik PVE provider
# Does not set up Traefik itself, do that elsewhere
pve_traefik_provider_setup_enable: false
# Where to get provider config
pve_traefik_provider_src_path: 'traefik-provider.yml.j2'
# Where to put provider config
pve_traefik_provider_dst_path: '/etc/traefik/provider/pve.yml'
# Enable Let's Encrypt for the service
# Only do this if PVE is publicly accessible
pve_traefik_letsencrypt_enable: false
