- name: Run IPTables script
  command: '/etc/iptables/config.sh'

- name: Restart IPTables-related services
  vars:
    services:
      - docker
      - fail2ban
  loop: '{{ services }}'
  when: 'iptables_config.changed and item + ".service" in service_facts.ansible_facts.services and service_facts.ansible_facts.services[item + ".service"].state == "running"'
  service:
    name: '{{ item }}.service'
    state: restarted
