- name: Check if supported machine type
  when: 'not (
    linux_server_machine_type == "bare-metal"
    or linux_server_machine_type == "raspi"
    or linux_server_machine_type == "qemu-vm"
    or linux_server_machine_type == "generic-vm"
    )'
  fail:
    msg: 'Unsupported OS: {{ ansible_distribution }} {{ ansible_distribution_version }}'

- name: Check if supported OS
  when: 'not (
    (ansible_distribution == "Debian" and ansible_distribution_version == "10")
    or (ansible_distribution == "Debian" and ansible_distribution_version == "11")
    )'
  fail:
    msg: 'Unsupported OS: {{ ansible_distribution }} {{ ansible_distribution_version }}'

- name: Get service facts
  service_facts: {}

- import_tasks: sudo.yml
- meta: flush_handlers

- import_tasks: packages.yml
- meta: flush_handlers

- import_tasks: unattended-upgrades.yml
- meta: flush_handlers

- import_tasks: networking.yml
- meta: flush_handlers

- import_tasks: iptables.yml
- meta: flush_handlers

- import_tasks: dns.yml
- meta: flush_handlers

- import_tasks: ntp.yml
- meta: flush_handlers

- import_tasks: hostname.yml
- meta: flush_handlers

- import_tasks: users.yml
- meta: flush_handlers

- import_tasks: ssh.yml
- meta: flush_handlers

- import_tasks: logging.yml
- meta: flush_handlers

- import_tasks: l10n.yml
- meta: flush_handlers

- import_tasks: banner.yml
- meta: flush_handlers

- import_tasks: fail2ban.yml
  when: 'linux_server_fail2ban_enable'
- meta: flush_handlers

- import_tasks: vim.yml
  when: 'linux_server_vim_setup_enable'
- meta: flush_handlers

- import_tasks: misc.yml
- meta: flush_handlers

# TODO:
# - See desktop notes.
# - Cloud-Init: Remove the Cloud-Init user. The username varies, for Debian cloudgeneric it's "debian".
# - Cloud-Init: Remove /etc/sudoers.d/90-cloud-init-users.
# - Cloud-Init: Remove /root/.ssh/authorized_keys to remove the "Please login as the user [...]" stuff.
# - Clout-Init: Uninstall, we don't need it any longer.
# - Debian cloudgeneric: "/etc/resolv.conf: symbolic link to ../run/resolvconf/resolv.conf". Uninstall resolvconf. DNS is broken, but that is probably because it copied the (local) DNS entries from the host.

- name: TODO Cloud-Init
  when: 'linux_server_machine_type == "qemu-vm"'
  fail: msg='TODO'
