# Setup packages

- name: Enable contrib and non-free archive areas
  replace:
    path: /etc/apt/sources.list
    regexp: '^(deb|deb-src)\s+(\S+)\s+(\S+)\s+.*main.*'
    replace: '\1 \2 \3 main contrib non-free'
    backup: true
  register: apt_enable_repo_areas

- name: Update if changed repo areas
  when: 'apt_enable_repo_areas.changed'
  apt: update_cache=true

- name: Install basic packages
  apt:
    name:
      - python3
      - python3-pip
      - ca-certificates
      - software-properties-common
      - curl
      - vim
      - htop
      - screen
      - tree
      - bash-completion
      - rsync

- name: Install machine type-specific packages (physical)
  when: 'linux_server_machine_type == "physical"'
  apt:
    name:
      - firmware-linux
      - smartmontools
      - lm-sensors

- name: Install machine type-specific packages (QEMU VM)
  when: 'linux_server_machine_type == "qemu-vm"'
  apt:
    name:
      - qemu-guest-agent

- name: Enable QEMU guest agent (QEMU VM)
  when: 'linux_server_machine_type == "qemu-vm"'
  systemd:
    name: qemu-guest-agent.service
    enabled: true
    state: started

- name: Install machine type-specific packages (RasPi)
  when: 'linux_server_machine_type == "raspi"'
  apt:
    name:
      - lm-sensors
