# Setup Docker

# Based on: https://docs.docker.com/engine/install/debian/

- name: Make sure Docker is NOT installed
  when: '"docker" in ansible_facts.packages
      or "docker-engine" in ansible_facts.packages
      or "docker.io" in ansible_facts.packages
      or "containerd" in ansible_facts.packages
      or "runc" in ansible_facts.packages'
  fail:
    msg: 'Old Docker is installed. Please remove it first.'

- name: Install Docker (block)
  when: '"docker-ce" not in ansible_facts.packages'
  block:
    - name: Get arch for repo
      shell: 'dpkg --print-architecture'
      changed_when: false
      register: docker_dpkg_arch_result

    - name: Get OS info
      shell: '. /etc/os-release; echo $ID; echo $VERSION_ID; echo $VERSION_CODENAME'
      changed_when: false
      register: docker_os_info_result

    - name: Add GPG keyring for APT repo
      vars:
        os_distro: '{{ docker_os_info_result.stdout_lines[0] }}'
      shell: 'curl -sSf https://download.docker.com/linux/{{ os_distro }}/gpg | gpg --dearmor > {{ docker_repo_keyring_path }}'

    - name: Create repo file
      vars:
        os_distro: '{{ docker_os_info_result.stdout_lines[0] }}'
        dpkg_arch: '{{ docker_dpkg_arch_result.stdout_lines[0] }}'
        os_version_codename: '{{ docker_os_info_result.stdout_lines[2] }}'
      copy:
        content: "deb [arch={{ dpkg_arch }} signed-by={{ docker_repo_keyring_path }}] https://download.docker.com/linux/{{ os_distro }} {{ os_version_codename }} stable\n"
        dest: '{{ docker_repo_path }}'

    - name: Update cache
      apt:
        update_cache: true

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io

- name: Setup Docker daemon config
  template:
    src: '{{ docker_config_src }}'
    dest: '/etc/docker/daemon.json'
    backup: true
  notify: Restart docker.service

- name: Enable Docker service
  service:
    name: docker.service
    enabled: yes
    state: started

- name: Check swap limit support
  shell: 'docker info | grep "WARNING: No swap limit support"'
  register: docker_swap_limit_result
  changed_when: no
  failed_when: no
  ignore_errors: yes

- name: Add swap limit support in GRUB config
  when: 'docker_swap_limit_result.rc == 0'
  script: file-sh-var-space-list-append.sh /etc/default/grub GRUB_CMDLINE_LINUX cgroup_enable=memory swapaccount=1
  notify: Update GRUB

- name: Warn about swap limit support changes
  when: 'docker_swap_limit_result.rc == 0'
  fail:
    msg: 'Swap limit support is not enabled yet, reboot required.'
  ignore_errors: yes

- name: Verify Docker
  shell: 'docker run --rm hello-world'
  changed_when: no

- name: Verify NVIDIA Container Runtime
  when: 'docker_nvidia_runtime_enable'
  shell: 'docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi'
  changed_when: no
