# Setup NVIDIA Container Toolkit for Docker

- name: Collect package facts
  package_facts:
    manager: apt

- name: Install NVIDIA Container Toolkit (NCT) for Docker (block)
  when: '"nvidia-docker2" not in ansible_facts.packages'
  block:
    - name: Get the distribution for NCT
      shell: '. /etc/os-release; echo $ID$VERSION_ID'
      changed_when: false
      register: docker_nvidia_runtime_distribution_result

    - name: Add NCT APT GPG keyring
      shell: 'curl -sSf https://nvidia.github.io/nvidia-docker/gpgkey | gpg --dearmor > /usr/share/keyrings/nvidia-docker-archive-keyring.gpg'
      args:
        warn: false

    - name: Add NCT APT GPG repo
      vars:
        distribution: '{{ docker_nvidia_runtime_distribution | default(docker_nvidia_runtime_distribution_result.stdout_lines[0]) }}'
      get_url:
        url: 'https://nvidia.github.io/nvidia-docker/{{ distribution }}/nvidia-docker.list'
        dest: /etc/apt/sources.list.d/nvidia-docker.list

    - name: Add keyring to repo file
      replace:
        path: /etc/apt/sources.list.d/nvidia-docker.list
        regexp: '^(.*)(deb|deb-src) +(http.*)$'
        replace: '\1\2 [signed-by=/usr/share/keyrings/nvidia-docker-archive-keyring.gpg] \3'

    - name: Update cache
      apt:
        update_cache: true

    - name: Install NCT
      apt:
        name:
          - nvidia-docker2
      notify: Restart docker.service

  always:
    - name: Delete temporary download file
      when: 'docker_nvidia_runtime_tmpfile is defined'
      file:
        path: "{{ docker_nvidia_runtime_tmpfile.path }}"
        state: absent
