# Setup NVIDIA Container Toolkit for Docker

# Based on: https://nvidia.github.io/nvidia-container-runtime/

- name: Install NVIDIA Container Toolkit (NCT) for Docker (block)
  when: '"nvidia-container-toolkit" not in ansible_facts.packages'
  block:
    - name: Get the distribution for NCT
      shell: '. /etc/os-release; echo $ID$VERSION_ID'
      changed_when: false
      register: docker_nvidia_runtime_distribution_result

    - name: Add NCT GPG keyring
      shell: 'curl -sSf https://nvidia.github.io/nvidia-container-runtime/gpgkey | gpg --dearmor > {{ docker_nvidia_runtime_repo_keyring_path }}'
      args:
        warn: false

    - name: Add NCT APT repo
      vars:
        distribution: '{{ docker_nvidia_runtime_distribution | default(docker_nvidia_runtime_distribution_result.stdout_lines[0]) }}'
      get_url:
        url: 'https://nvidia.github.io/nvidia-container-runtime/{{ distribution }}/nvidia-container-runtime.list'
        dest: '{{ docker_nvidia_runtime_repo_path }}'

    - name: Add keyring to repo file
      replace:
        path: '{{ docker_nvidia_runtime_repo_path }}'
        regexp: '^(.*)(deb|deb-src) +(http.*)$'
        replace: '\1\2 [signed-by={{ docker_nvidia_runtime_repo_keyring_path }}] \3'

    - name: Update cache
      apt:
        update_cache: true

    - name: Install NCT
      apt:
        name:
          - nvidia-container-toolkit
      notify: Restart docker.service

- name: Remove the older nvidia-docker2
  apt:
    state: absent
    name:
      - nvidia-docker2
  notify: Restart docker.service

# Bugfix, see https://github.com/NVIDIA/nvidia-docker/issues/1399
- name: Fix the ldconfig bug (Debian)
  when: 'ansible_distribution == "Debian"'
  community.general.ini_file:
    path: /etc/nvidia-container-runtime/config.toml
    section: nvidia-container-cli
    option: ldconfig
    value: '"/sbin/ldconfig"'

- name: Verify
  shell: 'docker run --rm hello-world'
  changed_when: no
