# Docker
docker_repo_keyring_path: "/usr/share/keyrings/docker-archive-keyring.gpg"
docker_repo_path: "/etc/apt/sources.list.d/docker.list"

# NVIDIA Container Toolkit
docker_nvidia_runtime_repo_keyring_path: "/usr/share/keyrings/nvidia-docker-archive-keyring.gpg"
docker_nvidia_runtime_repo_path: "/etc/apt/sources.list.d/nvidia-container-runtime.list"

# Docker compose
docker_compose_binary_path: /usr/local/bin/docker-compose
docker_compose_command_completion_path: /etc/bash_completion.d/docker-compose
