# Path to a VyOS config template using set-style commands. Defaults to internal config.
vyos_config_path: "vyos.cfg.j2"
# Debug option to keep temporary configs on disk after exit and print their paths.
vyos_config_keep_tmpfiles: false

# List of bogon prefixes, may be used for traffic and route filters.
vyos_config_bogons_ipv4:
  - "0.0.0.0/8"
  - "100.64.0.0/10"
  - "127.0.0.0/8"
  - "169.254.0.0/16"
  - "192.0.0.0/24"
  - "192.0.2.0/24"
  - "198.18.0.0/15"
  - "198.51.100.0/24"
  - "203.0.113.0/24"
  - "240.0.0.0/4"
vyos_config_bogons_ipv6:
  - "::/8"
  - "64:ff9b::/96"
  - "100::/64"
  - "200::/7"
  - "2001::/23"
  - "2001:2::/48"
  - "2001:db8::/32"
  - "2001:10::/28"
  - "2002::/16"
  - "3ffe::/16"
  - "fec0::/10"
