# Setup localization (l10n)

- name: Generate locale
  community.general.locale_gen:
    name: '{{ linux_locale }}'
    state: present

- name: Set default locale
  lineinfile:
    path: /etc/default/locale
    create: true
    regexp: '^LANG='
    line: 'LANG={{ linux_locale }}'
    mode: '0644'

- name: Install keyboard configuration program
  apt:
    name: keyboard-configuration

- name: Set keyboard configuration
  with_items:
    - { key: XKBMODEL, value: '{{ linux_l10n_keyboard.model }}' }
    - { key: XKBLAYOUT, value: '{{ linux_l10n_keyboard.layout }}' }
    - { key: XKBVARIANT, value: '{{ linux_l10n_keyboard.variant }}' }
    - { key: XKBOPTIONS, value: '{{ linux_l10n_keyboard.options }}' }
    - { key: BACKSPACE, value: '{{ linux_l10n_keyboard.backspace }}' }
  when: 'linux_machine_type == "bare-metal" or linux_machine_type == "raspi"'
  lineinfile:
    path: /etc/default/keyboard
    regexp: '^{{ item.key }}='
    line: '{{ item.key }}="{{ item.value }}"'
    mode: '0644'
  notify: Update keyboard configuration

- name: Set timezone
  community.general.timezone:
    name: '{{ linux_timezone }}'
