# Setup SSHD

- name: Disable root login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?\s*PermitRootLogin .+$'
    line: 'PermitRootLogin no'
    mode: '0644'
    validate: 'sshd -t -f %s'
  notify: Restart sshd.service

- name: Enable password login
  when: 'linux_sshd_password_auth_enable'
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?\s*PasswordAuthentication .+$'
    line: 'PasswordAuthentication yes'
    mode: '0644'
    validate: 'sshd -t -f %s'
  notify: Restart sshd.service

- name: Disable password login
  when: 'not linux_sshd_password_auth_enable'
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?\s*PasswordAuthentication .+$'
    line: 'PasswordAuthentication no'
    mode: '0644'
    validate: 'sshd -t -f %s'
  notify: Restart sshd.service

- name: Disable reverse DNS lookup
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?\s*UseDNS .+$'
    line: 'UseDNS no'
    mode: '0644'
    validate: 'sshd -t -f %s'
  notify: Restart sshd.service

# Disable locales to avoid annoying missing locale errors
- name: Disable SSH user locales
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?\s*AcceptEnv LANG LC_\*$'
    line: '#AcceptEnv LANG LC_*'
    mode: '0644'
    validate: 'sshd -t -f %s'
  notify: Restart sshd.service

- name: Set banner location
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?\s*Banner .+$'
    line: 'Banner /etc/issue.net'
    mode: '0644'
    validate: 'sshd -t -f %s'
  notify: Restart sshd.service
