# Setup PVE VMs

- name: Update VM lists
  include_tasks: pve-update-vms.yml

- name: Setup VMs
  loop: '{{ pve_vms }}'
  loop_control:
    loop_var: vm
    label: '{{ vm.name }} ({{ vm.type }})'
  vars:
    vm_id: '{{ pve_vmid_normal_next }}'
  when: '(not vm_id in pve_vm_ids) and (not vm.name in pve_vm_names)'
  include_tasks: 'pve-vms-{{ vm.type }}.yml'
