# Setup PVE template VMs

- name: Download ISO images
  loop: '{{ pve_iso_images }}'
  loop_control:
    loop_var: image
    label: '{{ image.name }}'
  vars:
    dest: '{{ pve_storage_default_iso_vztmpl_path }}/template/iso/{{ image.download_url | basename }}'
  get_url:
    url: '{{ image.download_url }}'
    dest: '{{ dest }}'
    checksum: '{{ image.checksum | default(omit) }}'
    timeout: '{{ pve_download_timeout_s }}'

- name: Download CT templates
  loop: '{{ pve_ct_templates }}'
  loop_control:
    loop_var: template
    label: '{{ template.name }}'
  vars:
    dest: '{{ pve_storage_default_iso_vztmpl_path }}/template/cache/{{ template.image_download_url | basename }}'
  get_url:
    url: '{{ template.image_download_url }}'
    dest: '{{ dest }}'
    checksum: '{{ template.image_checksum | default(omit) }}'
    timeout: '{{ pve_download_timeout_s }}'

- name: Update VM lists
  include_tasks: pve-update-vms.yml
