- name: Install Docker SDKs for Python
  pip:
    name:
      - docker
      - docker-compose

- name: Download Docker Compose
  get_url:
    url: 'https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64'
    dest: '{{ docker_compose_binary_path }}'
    mode: '0755'

- name: Make sure command completion dir exists
  file:
    path: '{{ docker_compose_command_completion_path | dirname }}'
    state: directory
    mode: '0755'

- name: Install Docker Compose command completion
  get_url:
    url: 'https://raw.githubusercontent.com/docker/compose/{{ docker_compose_version }}/contrib/completion/bash/docker-compose'
    dest: '{{ docker_compose_command_completion_path }}'
    mode: '0644'
