# Setup PVE groups, users and permissions

- name: "Check if PVE token file exists"
  stat:
    path: "/etc/pve/priv/token.cfg"
  register: "pve_token_file_exists_result"

- name: "Create PVE token file"
  when: "not pve_token_file_exists_result.stat.exists"
  file:
    path: "/etc/pve/priv/token.cfg"
    state: "touch"
    mode: "0600"

- name: "Setup PVE tokens"
  no_log: true
  template:
    src: "token.cfg.j2"
    dest: "/etc/pve/priv/token.cfg"
    owner: "root"
    mode: "0600"
