# Setup PVE firewall configs

- name: Create PVE firewall dir
  file:
    path: '/etc/pve/firewall'
    state: directory
    mode: '0755'

- name: Check if PVE cluster firewall file exists
  stat:
    path: '/etc/pve/firewall/cluster.fw'
  register: pve_firewall_cluster_file_exists_result

- name: Create PVE cluster firewall file
  when: 'not pve_firewall_cluster_file_exists_result.stat.exists'
  file:
    path: '/etc/pve/firewall/cluster.fw'
    state: touch
    mode: '0640'

- name: Set PVE cluster firewall config
  template:
    src: '{{ pve_firewall_cluster_config_path }}'
    dest: '/etc/pve/firewall/cluster.fw'
    mode: '0640'

- name: Check if PVE host firewall file exists
  stat:
    path: '/etc/pve/local/host.fw'
  register: pve_firewall_host_file_exists_result

- name: Create PVE host firewall file
  when: 'not pve_firewall_host_file_exists_result.stat.exists'
  file:
    path: '/etc/pve/local/host.fw'
    follow: true
    state: touch
    mode: '0640'

- name: Set PVE host firewall config
  template:
    src: '{{ pve_firewall_host_config_path }}'
    dest: '/etc/pve/local/host.fw'
    mode: '0640'
    follow: true
