vyos_firewall_network_groups: []
# vyos_firewall_network_groups:
#   - name: 'TODO'
#     description: 'TODO, optional'
#     afi: 'ipv4'
#     members:
#       - address: '192.0.1.0/24'

vyos_firewall_network_groups_bogons:
  - name: 'bogons-4'
    afi: 'ipv4'
    members:
      - address: '0.0.0.0/8'
      - address: '100.64.0.0/10'
      - address: '127.0.0.0/8'
      - address: '169.254.0.0/16'
      - address: '192.0.0.0/24'
      - address: '192.0.2.0/24'
      - address: '198.18.0.0/15'
      - address: '198.51.100.0/24'
      - address: '203.0.113.0/24'
      - address: '240.0.0.0/4'
  - name: 'bogons-6'
    afi: 'ipv6'
    members:
      - address: '::/8'
      - address: '64:ff9b::/96'
      - address: '100::/64'
      - address: '200::/7'
      - address: '2001::/23'
      - address: '2001:2::/48'
      - address: '2001:db8::/32'
      - address: '2001:10::/28'
      - address: '2002::/16'
      - address: '3ffe::/16'
      - address: 'fec0::/10'

vyos_firewall_network_groups_all: '{{ vyos_firewall_network_groups_bogons + vyos_firewall_network_groups }}'

vyos_firewall_address_groups: []
# vyos_firewall_address_groups:
#   - name: 'TODO'
#     description: 'TODO, optional'
#     afi: 'ipv4'
#     members:
#       - address: '192.0.1.1'

vyos_firewall_address_groups_all: '{{ vyos_firewall_address_groups }}'

vyos_firewall_port_groups: []
# vyos_firewall_port_groups:
#   - name: 'TODO'
#     description: 'TODO, optional'
#     members:
#       - port: '50000-50999'

vyos_firewall_port_groups_all: '{{ vyos_firewall_port_groups }}'

# Note: The rule sets' names must end with "-4" or "-6" for IPv4 and IPv6 respectively.
# See: https://docs.ansible.com/ansible/latest/collections/vyos/vyos/vyos_firewall_rules_module.html
vyos_firewall_rule_sets: []
# vyos_firewall_rule_sets:
#   - name: 'example-4'
#     description: 'yolo'
#     default_action: accept
#     rules:
#       - number: 10
#         description: 'Drop bogons'
#         destination:
#           group:
#             network_group: 'bogons-4'
#         action: drop
#   - name: 'example-6'
#     description: 'yolo'
#     default_action: drop

vyos_firewall_rule_sets_all: '{{ vyos_firewall_rule_sets }}'
