# Setup ISC DHCP Server (IPv4+IPv6)

- name: Install ISC DHCP Server
  apt:
    name:
      - isc-dhcp-server

- name: Setup DHCPv4 interfaces
  lineinfile:
    path: /etc/default/isc-dhcp-server
    regexp: '^INTERFACESv4='
    line: 'INTERFACESv4="{% for interface in dhcp_server_ipv4_interfaces %}{% if loop.index >= 2 %} {% endif %}{{ interface }}{% endfor %}"'
    mode: '0644'
  notify: Restart isc-dhcp-server

- name: Setup DHCPv6 interfaces
  lineinfile:
    path: /etc/default/isc-dhcp-server
    regexp: '^INTERFACESv6='
    line: 'INTERFACESv6="{% for interface in dhcp_server_ipv6_interfaces %}{% if loop.index >= 2 %} {% endif %}{{ interface }}{% endfor %}"'
    mode: '0644'
  notify: Restart isc-dhcp-server

- name: Setup DHCPv4 config
  template:
    src: 'dhcpd.conf.j2'
    dest: '/etc/dhcp/dhcpd.conf'
    validate: 'dhcpd -4 -t -cf %s'
    mode: '0644'
  notify: Restart isc-dhcp-server

- name: Setup DHCPv6 config
  template:
    src: 'dhcpd6.conf.j2'
    dest: '/etc/dhcp/dhcpd6.conf'
    validate: 'dhcpd -6 -t -cf %s'
    mode: '0644'
  notify: Restart isc-dhcp-server

- name: Enable DHCPv4+v6 service
  service:
    name: isc-dhcp-server.service
    enabled: true
    state: started
