- name: Check for failed units
  shell: '/usr/bin/systemctl --failed | egrep "^0 loaded units listed."'
  changed_when: no

- name: Check if AppArmor is operational (Debian)
  when: 'ansible_facts["os_family"] == "Debian"
      and not linux_status_ignore_apparmor'
  shell: '/usr/sbin/apparmor_status --enabled'
  changed_when: no

- name: Check if reboot file present (Debian)
  when: 'ansible_facts["os_family"] == "Debian"
      and not linux_status_ignore_reboot_required'
  stat:
    path: /var/run/reboot-required
  register: linux_status_check_reboot_required
  failed_when: 'linux_status_check_reboot_required.stat.exists'
