# Cleanup Cloud-Init

- name: "Remove Cloud-Init packages"
  apt:
    name:
      - cloud-init
      - cloud-utils
      - cloud-guest-utils
    autoremove: true

- name: Remove Cloud-Init files
  loop:
    - "/etc/sudoers.d/90-cloud-init-users"
    - "/root/.ssh/authorized_keys"
    - "/etc/netplan/50-cloud-init.yaml"
  file:
    path: "{{ item }}"
    state: "absent"
