# Setup users

- name: Update system groups
  loop: '{{ linux_local_groups | dict2items }}'
  loop_control:
    label: "{{ item.key }}"
  when: 'not item.value.remove | default(false) and item.value.system | default(false)'
  group:
    name: '{{ item.key }}'
    system: true

- name: Update non-system groups
  loop: '{{ linux_local_groups | dict2items }}'
  loop_control:
    label: "{{ item.key }}"
  when: 'not item.value.remove | default(false) and not item.value.system | default(false)'
  group:
    name: '{{ item.key }}'
    system: false

- name: Get user groups
  getent:
    database: group

- name: Update system users
  loop: '{{ linux_local_users | dict2items }}'
  loop_control:
    label: "{{ item.key }}"
  when: 'not item.value.remove | default(false) and item.value.system | default(false)'
  user:
    name: '{{ item.key }}'
    groups: '{{ item.value.groups | default([]) | intersect(ansible_facts.getent_group) }}'
    shell: '/usr/sbin/nologin'
    system: true
    home: /nonexistent
    create_home: false

- name: Update non-system users
  loop: '{{ linux_local_users | dict2items }}'
  when: 'not item.value.remove | default(false) and not item.value.system | default(false)'
  loop_control:
    label: "{{ item.key }}"
  user:
    name: '{{ item.key }}'
    password: '{{ item.value.password_hash | default("*") }}'
    groups: '{{ item.value.groups | default([]) | intersect(ansible_facts.getent_group) }}'
    shell: '{{ item.value.shell | default("/bin/bash") }}'

- name: Remove old users
  loop: '{{ linux_local_users | dict2items }}'
  loop_control:
    label: "{{ item.key }}"
  when: 'item.value.remove | default(false)'
  user:
    name: '{{ item.key }}'
    state: absent
    remove: true

- name: Update users' authorized keys
  loop: '{{ linux_local_users | dict2items }}'
  loop_control:
    label: "{{ item.key }}"
  when: 'not item.value.remove | default(false) and item.value.ssh_keys is defined'
  authorized_key:
    user: '{{ item.key }}'
    key: '{{ item.value.ssh_keys }}'
    exclusive: true

# Do last to allow users to get removed from it first
- name: Remove groups
  loop: '{{ linux_local_groups | dict2items }}'
  loop_control:
    label: "{{ item.key }}"
  when: 'item.value.remove | default(false)'
  group:
    name: '{{ item.key }}'
    state: absent
