- import_tasks: dns.yml
- import_tasks: fail2ban.yml
- import_tasks: iptables.yml
- import_tasks: l10n.yml
- import_tasks: logging.yml
- import_tasks: ntp.yml
- import_tasks: ssh.yml
- import_tasks: unattended-upgrades.yml
