# Docker compose version to install
docker_compose_version: "1.29.2"
# Force is required to change details, but will recreate the network and kick off any containers
docker_network_force_update: false
docker_network_pools_ipv4_prefix: "10.194.0.0/16"
docker_network_default_bridge_ipv6_subnet: "fd34:93c7:6fa8:39f0::/64"
docker_default_dns_servers:
  - "1.1.1.1"
  - "2606:4700:4700::1111"
# Docker networks to create
docker_networks: []
# docker_networks:
#   - name: apps-general
#     driver: macvlan
#     parent_interface: '{{ networking_main_interface.name }}'
#     ipv4_subnet: '{{ networking_main_interface.ipv4_address | ansible.netcommon.ipaddr("network/prefix") }}'
#     ipv6_subnet: '{{ networking_main_interface.name | ansible.netcommon.ipaddr("network/prefix") }}'
#   - name: test2
#     driver: bridge
#     ipv4_subnet: 10.95.99.0/22
#     ipv6_subnet: fd87:d8aa:222:99::/64
# TODO
docker_network_nvidia_stuff: no
