# Setup hidepid

- name: Get adm GID
  shell: 'egrep "^adm:" /etc/group | cut -d: -f3'
  changed_when: no
  register: adm_gid_result

- name: Add proc mount with hidepid
  mount:
    src: 'proc'
    path: '/proc'
    fstype: 'proc'
    opts: 'defaults,hidepid=2,gid={{ adm_gid_result.stdout_lines[0] }}'
    state: mounted
    backup: true
  register: update_hidepid

- name: Warn about hidepid changes
  when: update_hidepid.changed
  fail:
    msg: 'Hidepid changed, manual system restart required to apply changes.'
  ignore_errors: yes
