- name: Check if supported OS
  when: 'not (
    (ansible_distribution == "Debian" and ansible_distribution_version == "10")
    or (ansible_distribution == "Debian" and ansible_distribution_version == "11")
    )'
  fail:
    msg: 'Unsupported OS: {{ ansible_distribution }} {{ ansible_distribution_version }}'

- name: Check if OS variable is set (legacy)
  when: 'linux_server_os is defined'
  fail: msg='The OS variable is no longer supported, please remove it and make sure everything still works as intended.'

- name: Get service facts
  service_facts: {}
  register: service_facts

- import_tasks: sudo.yml
- meta: flush_handlers
- import_tasks: basic_packages.yml
- meta: flush_handlers
- import_tasks: fail2ban.yml
- meta: flush_handlers
- import_tasks: hidepid.yml
  when: 'linux_server_hidepid_enable'
- meta: flush_handlers
- import_tasks: users.yml
- meta: flush_handlers
- import_tasks: banner.yml
- meta: flush_handlers
- import_tasks: ssh.yml
- meta: flush_handlers
- import_tasks: vim.yml
  when: 'linux_server_vim_setup_enable'
- meta: flush_handlers
- import_tasks: misc.yml
