- name: Restart postfix.service
  service:
    name: postfix.service
    state: restarted

- name: Update aliases database
  command: 'newaliases'

- name: Update SASL password database
  when: 'postfix_relay_username is defined and postfix_relay_password is defined'
  command: 'postmap {{ postfix_sasl_passwd_file }}'
