# You may want to override this to pin it.
# https://github.com/traefik/traefik/releases
traefik_version: "3.0.0"
# Extra args to pass to the binary.
traefik_args: []
# User Traefik should run as.
traefik_user_name: "traefik"
# Should we create the user or is it managed from elsewhere?
traefik_user_create: true
# Log and access log.
traefik_log_format: json
traefik_log_level: info
traefik_accesslog_format: json
traefik_accesslog_buffering_size: 100
# Email address to use for ACME, for email notifications (optional).
# traefik_acme_webmaster: example@example.net
# If we should use the staging server while testing to avoid getting rate limited by the production server.
traefik_staging_server_enable: false
# Enable the API endpoint (port 8081), with optional IP allowlist.
traefik_api_enable: false
traefik_api_allowlist: ["0.0.0.0/0", "::/0"]
# Enable the dashboard endpoint (port 8081), with optional IP allowlist.
traefik_dashboard_enable: false
traefik_dashboard_allowlist: ["0.0.0.0/0", "::/0"]
# Enable the Prometheus metrics endpoint (port 8082), with optional IP allowlist.
traefik_metrics_enable: false
traefik_metrics_allowlist: ["0.0.0.0/0", "::/0"]
# Enable the ping endpoint (port 8083), with optional IP allowlist.
traefik_ping_enable: false
traefik_ping_allowlist: ["0.0.0.0/0", "::/0"]
# Extra TCP/UDP entrypoints to create, e.g. for sFlow:
traefik_extra_tcpudp_entrypoints: {}
# traefik_extra_tcpudp_entrypoints:
#   sflow: ":6343/udp"
# Enable a default provider, which will respond with a 404.
traefik_default_provider_enable: false
# Enable Let's Encrypt certs for the default provider.
traefik_default_provider_letsencrypt_enable: false
# If the Docker provider should be enabled (Docker must be installed first).
# Will also add the Traefik user to the Docker group.
traefik_provider_docker_enable: false
# Extra file provider config templates to add.
# The dst path should only include the filename itself, not path prefix.
# The src path is required if the type is template or copy.
# The keep type is for when the file is managed externally, so we don't remove it.
traefik_provider_configs_extra: []
# traefik_provider_configs_extra:
#   - type: keep
#     dst: pve.yml
#   - type: template
#     src: ../pve_servers/traefik/yolo.yml
#     dst: yolo.yml
